version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: pgdb
    environment:
      - POSTGRES_DB=ampdb
      - POSTGRES_USER=amp
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "54320:5432"

  db_ui:
    image: adminer:latest
    container_name: adminer
    ports:
      - "9090:8080"

  app:
    build: .
    container_name: app
    command: >
      sh -c "pip3 install -r requirements.txt &&
             pip3 install -r requirements-dev.txt &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
volumes:
  postgres_data:
